name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      is_version: ${{ steps.check.outputs.is_version }}
    steps:
      - name: Check commit message
        id: check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "is_version=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_version=false" >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: check-version
    if: needs.check-version.outputs.is_version == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --provenance --access public